server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    url: jdbc:mysql://localhost:3306/
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
      
transportation:
  url: http://localhost:8000/api/v1/transportation?truckId=  