spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:db
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

# :: CONNECTIVITY TO MYSQL ::
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 
#    url: jdbc:mysql://localhost:3306/
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
#    
    
transportation:
  url: http://localhost:8000/api/v1/transportation?truckId=  